### ISSUE TITLE
I need data

### ISSUE THREAD

**Issue by dd123-a** [sourcehold/Sourcehold#107]
Can someone tell me how to obtain the data file, or can you send me a copy directly. I'm stuck in the last step, God bless me

**Comment by dd123-a** [comment]
actually，i need stronghold.mlb

**Comment by gynt** [comment]
The data file is a data directory. The data directory contains the files from the stronghold game. You can buy the game here https://store.steampowered.com/app/40950/Stronghold_HD/

If you already have the game on Steam, you can let Steam verify the contents of the game folder, and you should find your .mlb, because it is part of the files in the Steam version: https://steamdb.info/depot/40957/

**Comment by dd123-a** [comment]
> The data file is a data directory. The data directory contains the files from the stronghold game. You can buy the game herehttps://store.steampowered.com/app/40950/Stronghold_HD/
> 
> If you already have the game on Steam, you can let Steam verify the contents of the game folder, and you should find your .mlb, because it is part of the files in the Steam version:https://steamdb.info/depot/40957/

I downloaded the game from the link you provided and obtained the data, but there is no logo2.tex in the data, and when running the exe, there is no option to play
